# Generated by Django 5.2.16 on 2026-07-24 18:22

import apps.assets.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('public_token', models.CharField(default=apps.assets.models.generate_public_token, max_length=48, unique=True)),
                ('entry_type', models.CharField(choices=[('purchase', 'Compra'), ('own_creation', 'Creación propia'), ('donation', 'Regalo o donación'), ('rental', 'Alquiler')], max_length=20)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('condition', models.CharField(max_length=40)),
                ('criticality', models.CharField(default='Media', max_length=20)),
                ('administrative_status', models.CharField(default='Registrado', max_length=30)),
                ('operational_status', models.CharField(default='No evaluado', max_length=30)),
                ('assignment_status', models.CharField(default='Pendiente', max_length=30)),
                ('entry_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zone', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=100)),
                ('specific_location', models.CharField(blank=True, max_length=160)),
                ('common_space', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('zone', 'building', 'area', 'room'), name='uq_asset_location')],
            },
        ),
        migrations.CreateModel(
            name='AssignableResponsible',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PERSONA', 'Persona'), ('AREA', 'Área'), ('ESPACIO_COMUN', 'Espacio común')], max_length=20)),
                ('external_reference', models.CharField(max_length=60, unique=True)),
                ('display_name', models.CharField(max_length=160)),
                ('area_name', models.CharField(blank=True, max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assets.location')),
            ],
        ),
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='ACTIVA', max_length=20)),
                ('change_reason', models.TextField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='assets.asset')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.assignableresponsible')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assets.location')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assets.location'),
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=80)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('asset_type', 'category', 'subcategory'), name='uq_asset_taxonomy')],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='taxonomy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assets.taxonomy'),
        ),
        migrations.AddConstraint(
            model_name='assignableresponsible',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('location__isnull', False), ('type', 'ESPACIO_COMUN')), models.Q(models.Q(('type', 'ESPACIO_COMUN'), _negated=True), ('location__isnull', True)), _connector='OR'), name='ck_common_space_location'),
        ),
        migrations.AddConstraint(
            model_name='assetassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVA')), fields=('asset',), name='uq_active_assignment_per_asset'),
        ),
        migrations.AddConstraint(
            model_name='assetassignment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVA', 'FINALIZADA', 'ANULADA'])), name='ck_assignment_status'),
        ),
    ]
