# Generated by Django 5.2.16 on 2026-07-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='assignment_status',
            field=models.CharField(default='Sin asignar', max_length=30),
        ),
    ]
