# Generated by Django 5.2.16 on 2026-07-31 16:32

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_seed_normalized_taxonomy'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('version', models.CharField(max_length=40)),
                ('level_name', models.CharField(max_length=100)),
                ('source_filename', models.CharField(max_length=255)),
                ('source_sha256', models.CharField(max_length=64)),
                ('image', models.FileField(upload_to='facility_plans/')),
                ('min_x', models.DecimalField(decimal_places=6, max_digits=20)),
                ('min_y', models.DecimalField(decimal_places=6, max_digits=20)),
                ('max_x', models.DecimalField(decimal_places=6, max_digits=20)),
                ('max_y', models.DecimalField(decimal_places=6, max_digits=20)),
                ('active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacilityPlanMarker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_index', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('raw_code', models.CharField(blank=True, max_length=64)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('layer', models.CharField(blank=True, max_length=120)),
                ('source_x', models.DecimalField(decimal_places=6, max_digits=20)),
                ('source_y', models.DecimalField(decimal_places=6, max_digits=20)),
                ('normalized_x', models.DecimalField(decimal_places=8, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('normalized_y', models.DecimalField(decimal_places=8, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('status', models.CharField(choices=[('MATCHED', 'Vinculado'), ('TAXONOMY_ONLY', 'Solo taxonomía'), ('PLACEHOLDER', 'Marcador pendiente'), ('UNKNOWN', 'Desconocido')], default='UNKNOWN', max_length=20)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.asset')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='assets.facilityplan')),
                ('taxonomy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assets.taxonomy')),
            ],
            options={
                'indexes': [models.Index(fields=['plan', 'status'], name='idx_marker_plan_status'), models.Index(fields=['plan', 'taxonomy'], name='idx_marker_plan_tax'), models.Index(fields=['raw_code'], name='idx_marker_raw_code')],
                'constraints': [models.UniqueConstraint(fields=('plan', 'source_index'), name='uq_plan_marker_source'), models.CheckConstraint(condition=models.Q(('normalized_x__gte', 0), ('normalized_x__lte', 1)), name='ck_marker_norm_x'), models.CheckConstraint(condition=models.Q(('normalized_y__gte', 0), ('normalized_y__lte', 1)), name='ck_marker_norm_y')],
            },
        ),
    ]
