# Generated by Django 5.2.16 on 2026-07-31 18:17

import apps.assets.storage
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_private_facility_plan_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='location_marker_x',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))]),
        ),
        migrations.AddField(
            model_name='asset',
            name='location_marker_y',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))]),
        ),
        migrations.CreateModel(
            name='LocationMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('image', models.FileField(storage=apps.assets.storage.PrivateLocationMapStorage(), upload_to='location_maps/')),
                ('original_filename', models.CharField(max_length=255)),
                ('image_sha256', models.CharField(max_length=64)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=240)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reference_maps', to='assets.location')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='location_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.locationmap'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('location_map__isnull', True), ('location_marker_x__isnull', True), ('location_marker_y__isnull', True)), models.Q(('location_map__isnull', False), ('location_marker_x__isnull', False), ('location_marker_y__isnull', False)), _connector='OR'), name='ck_asset_location_marker_pair'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('location_marker_x__isnull', True), models.Q(('location_marker_x__gte', 0), ('location_marker_x__lte', 1)), _connector='OR'), name='ck_asset_location_marker_x'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('location_marker_y__isnull', True), models.Q(('location_marker_y__gte', 0), ('location_marker_y__lte', 1)), _connector='OR'), name='ck_asset_location_marker_y'),
        ),
        migrations.AddIndex(
            model_name='locationmap',
            index=models.Index(fields=['location', 'active'], name='idx_location_map_active'),
        ),
        migrations.AddConstraint(
            model_name='locationmap',
            constraint=models.UniqueConstraint(fields=('location', 'version'), name='uq_location_map_version'),
        ),
        migrations.AddConstraint(
            model_name='locationmap',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('location',), name='uq_active_map_per_location'),
        ),
    ]
