# Generated by Django 5.2.16 on 2026-08-09 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_asset_photo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='location',
            name='uq_asset_location',
        ),
        migrations.AddField(
            model_name='location',
            name='headcount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Usuarios (Capacidad)'),
        ),
        migrations.AddField(
            model_name='location',
            name='level',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='site',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='square_meters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tamaño (m2)'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('site', 'zone', 'building', 'level', 'area', 'room', 'location_code'), name='uq_asset_location'),
        ),
    ]
