# Generated by Django 5.2 on 2026-08-12

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0010_remove_location_uq_asset_location_location_headcount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildingArea",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("site", models.CharField(blank=True, default="", max_length=100)),
                ("zone", models.CharField(max_length=100)),
                ("building", models.CharField(max_length=100)),
                ("square_meters", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="Tamaño del edificio (m2)")),
            ],
            options={
                "verbose_name": "Superficie de edificio",
                "verbose_name_plural": "Superficies de edificios",
            },
        ),
        migrations.AddConstraint(
            model_name="buildingarea",
            constraint=models.UniqueConstraint(fields=("site", "zone", "building"), name="uq_building_area_identity"),
        ),
    ]
