# Generated by Django 5.2.16 on 2026-08-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_buildingarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingarea',
            name='square_meters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='TamaÃ±o del edificio (m2)'),
        ),
    ]
