# Generated by Django 5.2.16 on 2026-08-14 19:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_buildingarea_space_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomyFamily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='El código de la familia debe usar solo A-Z y 0-9.', regex='^[A-Z0-9]+$')])),
                ('name', models.CharField(max_length=160)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Taxonomy families',
                'ordering': ('code', 'name'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='taxonomy',
            name='ck_taxonomy_sequence_digits',
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='type_code',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='El código de tipo debe usar solo A-Z y 0-9.', regex='^[A-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='asset_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='prefix',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='types', to='assets.taxonomyfamily'),
        ),
        migrations.AddConstraint(
            model_name='taxonomy',
            constraint=models.CheckConstraint(condition=models.Q(('sequence_digits__gte', 2), ('sequence_digits__lte', 8)), name='ck_taxonomy_sequence_digits'),
        ),
        migrations.AddConstraint(
            model_name='taxonomy',
            constraint=models.UniqueConstraint(fields=('family', 'type_code'), name='uq_taxonomy_family_type'),
        ),
    ]
