# Generated by Django 5.2.16 on 2026-08-14 19:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_taxonomyfamily_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomyPart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('part_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El código debe usar solo A-Z y 0-9.', regex='^[A-Z0-9]+$')])),
                ('name', models.CharField(max_length=160)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='assets.taxonomy')),
            ],
            options={
                'ordering': ('part_code', 'name'),
                'unique_together': {('taxonomy', 'part_code')},
            },
        ),
        migrations.CreateModel(
            name='TaxonomyPiece',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('piece_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El código debe usar solo A-Z y 0-9.', regex='^[A-Z0-9]+$')])),
                ('name', models.CharField(max_length=160)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='assets.taxonomypart')),
            ],
            options={
                'ordering': ('piece_code', 'name'),
                'unique_together': {('part', 'piece_code')},
            },
        ),
    ]
