# Generated by Django 5.2.16 on 2026-08-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0016_taxonomypart_taxonomypiece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomy',
            name='sequence_digits',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='specialty',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
