import { FloppyDisk, PencilSimple, Plus, UserGear, UsersThree } from "@phosphor-icons/react";
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { createTechnician, listTechnicians, updateTechnician, type Technician, type TechnicianInput } from "@/modules/accounts/technicianRepository";
import { listWorkOrders } from "@/modules/workorders/workOrderRepository";

const emptyForm: TechnicianInput = { full_name: "", email: "", worker_code: "", dni: "", specialty: "", position: "", hourly_rate: 0, active: true, temporary_password: "" };

export function TechnicianManagementPage() {
  const [technicians, setTechnicians] = useState<Technician[]>([]);
  const [orders, setOrders] = useState<Awaited<ReturnType<typeof listWorkOrders>>>([]);
  const [editing, setEditing] = useState<Technician | null | undefined>();
  const [form, setForm] = useState<TechnicianInput>(emptyForm);
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);
  async function refresh() { const [people, work] = await Promise.all([listTechnicians(), listWorkOrders()]); setTechnicians(people); setOrders(work); }
  useEffect(() => { void refresh().catch(() => setError("No se pudo cargar el equipo técnico.")); }, []);
  function openEdit(person?: Technician) { setEditing(person ?? null); setForm(person ? { full_name: person.full_name, email: person.email, worker_code: person.worker_code, dni: person.dni, specialty: person.specialty, position: person.position || "", hourly_rate: Number(person.hourly_rate || 0), active: person.active, temporary_password: "" } : emptyForm); setError(""); }
  async function save(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { const input = { ...form, temporary_password: form.temporary_password || undefined }; if (editing) await updateTechnician(editing.id, input); else if (input.temporary_password) await createTechnician(input); else throw new Error("Define una contraseña temporal para el nuevo técnico."); await refresh(); setEditing(undefined); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "No se pudo guardar el perfil."); } finally { setSaving(false); } }
  return <section className="technician-management-page"><header className="page-heading"><div><p className="breadcrumb">Administración / Técnicos</p><h1>Equipo técnico</h1><p>Administra cargos, tarifas y perfiles. La cuota se calcula según las horas registradas en las OT.</p></div><button className="button button-primary" type="button" onClick={() => openEdit()}><Plus size={18} />Nuevo técnico</button></header>{error && <div className="form-error" role="alert">{error}</div>}
    <section className="technician-directory data-panel"><header><div><h2>Técnicos y tarifas</h2><p>La tarifa por hora es definida únicamente por el administrador.</p></div><UsersThree size={24} /></header><div className="table-scroll"><table><thead><tr><th>Técnico</th><th>Cargo / posición</th><th>OT / horas registradas</th><th>Tarifa por hora</th><th>Cuota acumulada</th><th>Estado</th><th aria-label="Acciones" /></tr></thead><tbody>{technicians.map((person) => { const workedMinutes = orders.filter((order) => order.operatorId === person.id).reduce((total, order) => total + (order.effectiveWorkMinutes || 0), 0); const cost = workedMinutes / 60 * Number(person.hourly_rate || 0); return <tr key={person.id}><td><Link className="technician-detail-link" to={`/administracion/tecnicos/${person.id}`}><strong>{person.full_name}</strong><small>{person.worker_code}</small></Link></td><td>{person.position || "Sin cargo"}<small>{person.specialty || "Sin especialidad"}</small></td><td><strong>{orders.filter((order) => order.operatorId === person.id).length} OT</strong><small>{Math.floor(workedMinutes / 60)} h {workedMinutes % 60} min</small></td><td><strong>S/ {Number(person.hourly_rate || 0).toFixed(2)}</strong><small>por hora trabajada</small></td><td><strong>S/ {cost.toFixed(2)}</strong><small>horas efectivas × tarifa</small></td><td><span className={`status ${person.active ? "status-success" : "status-neutral"}`}>{person.active ? "Activo" : "Inactivo"}</span></td><td><button className="icon-button" type="button" aria-label={`Editar ${person.full_name}`} onClick={() => openEdit(person)}><PencilSimple size={18} /></button></td></tr>; })}</tbody></table></div></section>
    {editing !== undefined && <aside className="technician-editor modal-widget" aria-labelledby="technician-editor-title"><header><UserGear size={24} /><div><h2 id="technician-editor-title">{editing ? "Editar técnico" : "Registrar técnico"}</h2><p>Define el cargo y el valor de su hora trabajada.</p></div><button className="icon-button" type="button" aria-label="Cerrar edición" onClick={() => setEditing(undefined)}>×</button></header><form onSubmit={save}><label className="field"><span>Nombre completo *</span><input required value={form.full_name} onChange={(event) => setForm({ ...form, full_name: event.target.value })} /></label><label className="field"><span>Código de trabajador *</span><input required value={form.worker_code} onChange={(event) => setForm({ ...form, worker_code: event.target.value })} /></label><label className="field"><span>DNI</span><input maxLength={8} value={form.dni} onChange={(event) => setForm({ ...form, dni: event.target.value })} /></label><label className="field"><span>Correo</span><input type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} /></label><label className="field"><span>Cargo / posición *</span><input required placeholder="Jefe, ayudante, especialista..." value={form.position} onChange={(event) => setForm({ ...form, position: event.target.value })} /></label><label className="field"><span>Especialidad</span><input value={form.specialty} onChange={(event) => setForm({ ...form, specialty: event.target.value })} placeholder="Electricista, gasfitero..." /></label><label className="field"><span>Tarifa por hora (S/) *</span><input required type="number" min="0" step="0.01" value={form.hourly_rate} onChange={(event) => setForm({ ...form, hourly_rate: Number(event.target.value) })} /><small>Se multiplica por las horas efectivamente registradas.</small></label><label className="field"><span>{editing ? "Nueva contraseña temporal" : "Contraseña temporal *"}</span><input type="password" minLength={10} required={!editing} value={form.temporary_password ?? ""} onChange={(event) => setForm({ ...form, temporary_password: event.target.value })} /></label><label className="switch-row"><input type="checkbox" checked={form.active} onChange={(event) => setForm({ ...form, active: event.target.checked })} /><span><strong>Perfil activo</strong><small>Puede recibir asignaciones y notificaciones.</small></span></label><button className="button button-primary" disabled={saving}><FloppyDisk size={18} />{saving ? "Guardando…" : "Guardar cambios"}</button></form></aside>}
  </section>;
}
