# Generated by Django 5.2.16 on 2026-07-27 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('prefijo', models.CharField(help_text='Prefijo de letras usado en el código de catálogo (ej. H, G, C).', max_length=3, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('medida', models.CharField(blank=True, max_length=100)),
                ('foto', models.ImageField(blank=True, help_text='Foto representativa del material (ej. foto genérica de un tornillo, o del modelo de taladro antes de generar sus piezas).', null=True, upload_to='materiales/')),
                ('grosor_mm', models.DecimalField(blank=True, decimal_places=2, help_text='Grosor/diámetro, si aplica (ej. brocas, pernos).', max_digits=6, null=True)),
                ('largo_mm', models.DecimalField(blank=True, decimal_places=2, help_text='Largo, si aplica (ej. brocas, pernos).', max_digits=6, null=True)),
                ('ubicacion_fisica', models.CharField(blank=True, help_text="Dónde encontrar este material físicamente, ej. 'Caja de brocas, Estante 3'.", max_length=100)),
                ('tipo_control', models.CharField(choices=[('retornable', 'Retornable'), ('no_retornable', 'No retornable')], max_length=15)),
                ('control_individual', models.BooleanField(default=False)),
                ('cantidad_total', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=5, unique=True)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Prestado', 'Prestado'), ('Mantenimiento', 'Mantenimiento'), ('Baja', 'Baja')], default='Disponible', max_length=15)),
                ('foto', models.ImageField(blank=True, help_text='Foto de esta pieza específica. Si es un estuche, es la foto del estuche completo; si es una pieza hija, es la foto de esa unidad.', null=True, upload_to='piezas/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='piezas', to='catalogo.material')),
                ('padre', models.ForeignKey(blank=True, help_text='Si esta pieza es contenedora (ej. estuche), aquí no aplica. Si esta pieza pertenece a un contenedor, aquí va la pieza padre.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piezas_hijas', to='catalogo.pieza')),
            ],
            options={
                'verbose_name_plural': 'Piezas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategorias', to='catalogo.categoria')),
            ],
            options={
                'verbose_name_plural': 'Subcategorías',
                'ordering': ['categoria__nombre', 'nombre'],
                'unique_together': {('categoria', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='material',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiales', to='catalogo.subcategoria'),
        ),
    ]
