# Generated by Django 5.2.16 on 2026-07-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='modelo',
            field=models.CharField(blank=True, help_text="Código o número de modelo del fabricante, si la herramienta lo tiene (ej. 'GSB 550').", max_length=100),
        ),
    ]
