# Generated by Django 5.2.16 on 2026-07-29 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_material_modelo'),
        ('inspeccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='plantilla_inspeccion',
            field=models.ForeignKey(blank=True, help_text='Plantilla de criterios a usar para inspeccionar materiales de esta subcategoría. Vacío si no aplica inspección (ej. consumibles).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='inspeccion.plantillacriterio'),
        ),
    ]
