# Generated by Django 5.2.16 on 2026-08-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_subcategoria_plantilla_inspeccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='es_componente',
            field=models.BooleanField(default=False, help_text='True si este material es un tipo de pieza componente de un estuche (creado automáticamente al registrar piezas hijas inline). Los componentes no aparecen en el catálogo general.'),
        ),
    ]
