# Generated by Django 5.2.16 on 2026-08-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_material_es_componente'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='requiere_inspeccion',
            field=models.BooleanField(default=False, help_text='Si está activo, los materiales de esta categoría pueden ser inspeccionados (ej. Herramientas). Categorías como consumibles o eléctricos no retornables deben dejarlo desactivado.'),
        ),
    ]
