# Generated by Django 5.2.16 on 2026-08-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_material_es_componente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieza',
            name='codigo',
            field=models.CharField(blank=True, default=None, max_length=5, null=True, unique=True),
        ),
    ]
