# Generated by Django 5.2.16 on 2026-08-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_categoria_requiere_inspeccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de referencia de este material. Para estuches, es el precio del conjunto completo (no de piezas hijas individuales).', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si se desactiva, los materiales de esta categoría dejarán de aparecer en préstamos, inspecciones y demás procesos operativos.'),
        ),
    ]
