# Generated by Django 5.2.16 on 2026-08-08 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_pieza_codigo_nullable'),
        ('catalogo', '0006_material_precio_alter_categoria_activo'),
    ]

    operations = [
    ]
