# Generated by Django 5.2.16 on 2026-08-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_merge_20260807_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='unidad_manejo',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('caja', 'Caja')], default='unidad', help_text='Cómo se cuenta el stock de este consumible: por unidad suelta o por caja.', max_length=10),
        ),
        migrations.AddField(
            model_name='material',
            name='unidades_por_caja',
            field=models.PositiveIntegerField(blank=True, help_text="Cuántas unidades trae cada caja. Requerido si unidad_manejo='caja'.", null=True),
        ),
    ]
