# Generated by Django 5.2.16 on 2026-08-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_merge_20260807_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='grosor_mm',
            new_name='grosor',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='largo_mm',
            new_name='largo',
        ),
        migrations.AddField(
            model_name='material',
            name='unidad_medida',
            field=models.CharField(choices=[('mm', 'Milímetros'), ('cm', 'Centímetros'), ('in', 'Pulgadas'), ('ft', 'Pies')], default='mm', help_text='Unidad usada para grosor y largo.', max_length=4),
        ),
    ]
