# Generated by Django 5.2.16 on 2026-08-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_rename_grosor_mm_material_grosor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='periodicidad_inspeccion_dias',
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='pieza',
            name='detalle',
            field=models.CharField(blank=True, help_text="Nombre o descripción libre para identificar esta pieza suelta individualmente (ej. 'Taladro de Juan', 'Estuche azul chico'). Opcional; se completa después de creada, no al momento del alta masiva.", max_length=150),
        ),
    ]
