# Generated by Django 5.2.16 on 2026-08-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_material_periodicidad_inspeccion_dias_pieza_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='periodicidad_unidad',
            field=models.CharField(choices=[('dias', 'Días'), ('meses', 'Meses')], default='meses', help_text="Unidad de la frecuencia: 'dias' o 'meses'.", max_length=5),
        ),
        migrations.AddField(
            model_name='material',
            name='periodicidad_valor',
            field=models.PositiveIntegerField(default=3, help_text='Número de la frecuencia de inspección (usar junto con periodicidad_unidad).'),
        ),
        migrations.AlterField(
            model_name='material',
            name='periodicidad_inspeccion_dias',
            field=models.PositiveIntegerField(default=90, editable=False, help_text='Calculado automáticamente desde periodicidad_valor/unidad. No se edita directo.'),
        ),
    ]
