# Generated by Django 5.2.16 on 2026-08-11 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_material_unidad_manejo_material_unidades_por_caja'),
        ('catalogo', '0010_material_periodicidad_unidad_and_more'),
    ]

    operations = [
    ]
