# Generated by Django 5.2.16 on 2026-08-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_merge_20260810_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='moneda',
            field=models.CharField(blank=True, choices=[('PEN', 'Soles (PEN)'), ('USD', 'Dólares (USD)')], default='PEN', help_text='Moneda en la que está expresado el precio.', max_length=3),
        ),
    ]
