# Generated by Django 5.2.16 on 2026-08-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_relabel_unidad_manejo_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='unidades_por_caja',
            field=models.PositiveIntegerField(blank=True, help_text="Cuántas unidades trae cada empaque. Requerido si unidad_manejo no es 'unidad'.", null=True),
        ),
    ]
