# Generated by Django 5.2.16 on 2026-08-12 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0015_alter_material_almacen'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='catalogo.almacen'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='prefijo',
            field=models.CharField(help_text='Prefijo de letras usado en el código de catálogo (ej. H, G, C).', max_length=3),
        ),
        migrations.AlterField(
            model_name='material',
            name='codigo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('almacen', 'nombre'), ('almacen', 'prefijo')},
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('almacen', 'codigo')},
        ),
    ]
