# Generated by Django 5.2.16 on 2026-08-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0016_catalogos_unidad_medida_manejo_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='unidades_por_caja',
            field=models.PositiveIntegerField(blank=True, help_text='Cuántas unidades trae cada empaque. Requerido si unidad_manejo.requiere_multiplicador.', null=True),
        ),
    ]
