# Generated by Django 5.2.16 on 2026-08-12 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0017_asignar_almacen_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='catalogo.almacen'),
        ),
    ]
