# Generated by Django 5.2.16 on 2026-08-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0018_alter_categoria_almacen'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='codigo_quipu',
            field=models.CharField(blank=True, help_text='Código de referencia manual del sistema QUIPU (opcional).', max_length=50, verbose_name='Código QUIPU'),
        ),
    ]
