# Generated by Django 5.2.16 on 2026-08-13 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0015_alter_material_tipo_control_and_more'),
        ('catalogo', '0018_alter_categoria_almacen'),
    ]

    operations = [
    ]
