# Generated by Django 5.2.16 on 2026-08-13 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0019_add_codigo_quipu_material'),
        ('catalogo', '0019_merge_20260813_0833'),
    ]

    operations = [
    ]
