# Generated by Django 5.2.16 on 2026-08-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0020_merge_20260813_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='tipo_control',
            field=models.CharField(choices=[('retornable', 'Retornable'), ('no_retornable', 'No retornable')], max_length=15),
        ),
    ]
