# Generated by Django 5.2.16 on 2026-08-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0021_alter_material_tipo_control_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='croquis',
            field=models.ImageField(blank=True, help_text='Plano/croquis del almacén, editable por Almacenero y Administrador.', null=True, upload_to='croquis/'),
        ),
    ]
