# Generated by Django 5.2.16 on 2026-08-13 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0015_material_clasificacion_operativa'),
        ('catalogo', '0021_alter_material_tipo_control_and_more'),
    ]

    operations = [
    ]
