# Generated by Django 5.2.16 on 2026-08-14 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0019_material_stock_minimo'),
        ('catalogo', '0021_alter_material_tipo_control_and_more'),
    ]

    operations = [
    ]
