# Generated by Django 5.2.16 on 2026-08-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0022_almacen_croquis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='codigo_quipu',
        ),
        migrations.AddField(
            model_name='material',
            name='codigo_ekipu',
            field=models.CharField(blank=True, help_text='Código de referencia manual del sistema EKIPU (opcional).', max_length=50, verbose_name='Código EKIPU'),
        ),
    ]
