# Generated by Django 5.2.16


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0022_almacen_croquis'),
        ('catalogo', '0022_merge_20260814_0626'),
    ]

    operations = [
    ]
