# Generated by Django 5.2.16 on 2026-08-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0022_merge_20260813_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='clasificacion_operativa',
            field=models.CharField(choices=[('CONSUMIBLE', 'Consumible (genera costo)'), ('HERRAMIENTA', 'Herramienta reutilizable (solo uso)'), ('EPP', 'Equipo de protección personal (solo uso)')], default='CONSUMIBLE', help_text='Define el tratamiento en una OT. Solo los consumibles generan costos; herramientas y EPP quedan registrados como uso operativo.', max_length=16),
        ),
    ]
