# Generated by Django 5.2.16 on 2026-08-19 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0022_merge_20260814_0626'),
        ('catalogo', '0023_remove_material_codigo_quipu_material_codigo_ekipu'),
    ]

    operations = [
    ]
