# Generated by Django 5.2.16 on 2026-08-20 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0024_merge_20260819_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMedidaCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(help_text="Identificador interno estable (ej. 'diametro'). No se muestra al usuario.", max_length=20, unique=True)),
                ('nombre', models.CharField(help_text="Ej. 'Diámetro'.", max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tipo de medida',
                'verbose_name_plural': 'Tipos de medida',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='material',
            name='grosor',
        ),
        migrations.RemoveField(
            model_name='material',
            name='largo',
        ),
        migrations.RemoveField(
            model_name='material',
            name='unidad_medida',
        ),
        migrations.CreateModel(
            name='MaterialMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medidas', to='catalogo.material')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medidas_material', to='catalogo.unidadmedida')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medidas_material', to='catalogo.tipomedidacatalogo')),
            ],
            options={
                'verbose_name': 'Medida de material',
                'verbose_name_plural': 'Medidas de material',
                'ordering': ['tipo__orden', 'tipo__nombre'],
                'unique_together': {('material', 'tipo')},
            },
        ),
    ]
