# Generated by Django 5.2.16 on 2026-08-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0026_seed_tipos_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='codigo_quipu',
            field=models.CharField(blank=True, help_text='Código de referencia del sistema QUIPU (opcional).', max_length=50, verbose_name='Código QUIPU'),
        ),
    ]
