# Generated by Django 5.2.16 on 2026-08-20 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0027_alter_material_codigo_quipu'),
        ('catalogo', '0027_vincular_plantillas_inspeccion'),
    ]

    operations = [
    ]
