# Generated by Django 5.2.16 on 2026-08-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0028_merge_20260820_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='stock_seguridad',
            field=models.PositiveIntegerField(default=0, help_text='Unidades extra de colchón (stock de seguridad).'),
        ),
        migrations.AddField(
            model_name='material',
            name='tiempo_entrega_dias',
            field=models.PositiveIntegerField(default=7, help_text='Días que tarda en llegar un pedido de reposición.'),
        ),
    ]
