# Generated by Django 5.2.16 on 2026-08-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0029_material_stock_seguridad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='tiempo_entrega_dias',
            field=models.PositiveIntegerField(default=7, help_text='Días hábiles (Lun–Vie) que tarda en llegar un pedido de reposición.'),
        ),
    ]
