# Generated by Django 6.0.4 on 2026-07-27 14:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_alter_asset_assignment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalDiagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_order_id', models.CharField(max_length=80, unique=True)),
                ('work_order_code', models.CharField(max_length=40)),
                ('evaluator_name', models.CharField(max_length=160)),
                ('result', models.CharField(choices=[('REPARABLE', 'Reparable'), ('NO_REPARABLE', 'No reparable'), ('REPAIR_NOT_VIABLE', 'Reparación no viable')], max_length=24)),
                ('description', models.TextField()),
                ('probable_cause', models.TextField(blank=True)),
                ('operational_risk', models.CharField(blank=True, max_length=20)),
                ('affected_components', models.TextField(blank=True)),
                ('technical_justification', models.TextField(blank=True)),
                ('estimated_repair_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estimated_current_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('evidence', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technical_diagnoses', to='assets.asset')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RetirementRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('recommendation', models.CharField(choices=[('VENTA', 'Venta'), ('RECICLAJE', 'Reciclaje'), ('DESECHO', 'Desecho'), ('DONACION', 'Donación')], max_length=16)),
                ('requested_by', models.CharField(max_length=160)),
                ('supervisor_name', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_EVALUACION', 'En evaluación'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('SUBSANACION', 'Requiere subsanación'), ('PENDIENTE_DISPOSICION', 'Pendiente de disposición'), ('CERRADA', 'Cerrada')], default='PENDIENTE', max_length=24)),
                ('decision_reason', models.TextField(blank=True)),
                ('decision_by', models.CharField(blank=True, max_length=160)),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('approved_method', models.CharField(blank=True, choices=[('VENTA', 'Venta'), ('RECICLAJE', 'Reciclaje'), ('DESECHO', 'Desecho'), ('DONACION', 'Donación')], max_length=16)),
                ('disposal', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retirement_requests', to='assets.asset')),
                ('diagnosis', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='retirement_request', to='lifecycle.technicaldiagnosis')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
