"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from corsheaders.defaults import default_headers

from .database import build_database_config


def env_list(name: str, default: str = "") -> list[str]:
    return [item.strip() for item in os.environ.get(name, default).split(",") if item.strip()]

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

DJANGO_ENV = os.environ.get("DJANGO_ENV", "development").strip().lower()
IS_PRODUCTION = DJANGO_ENV in {"production", "prod"}
DEBUG = os.environ.get("DJANGO_DEBUG", "0" if IS_PRODUCTION else "1") == "1"
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-local-only-change-before-production")

_local_hosts = ["localhost", "127.0.0.1", "testserver"]
ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", ",".join(_local_hosts) if DEBUG else "")
CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS")

if IS_PRODUCTION:
    if DEBUG:
        raise RuntimeError("DJANGO_DEBUG debe ser 0 en producción.")
    if SECRET_KEY.startswith("django-insecure-") or len(SECRET_KEY) < 50:
        raise RuntimeError("Define un DJANGO_SECRET_KEY aleatorio de al menos 50 caracteres en producción.")
    if not ALLOWED_HOSTS or any(host in _local_hosts for host in ALLOWED_HOSTS):
        raise RuntimeError("Define DJANGO_ALLOWED_HOSTS con los dominios reales de producción.")
    if not CSRF_TRUSTED_ORIGINS:
        raise RuntimeError("Define CSRF_TRUSTED_ORIGINS con las URL HTTPS públicas.")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "apps.accounts",
    "apps.audit",
    "apps.documents",
    "apps.assets",
    "apps.spaces",
    "apps.taxonomy",
    "apps.assignments",
    "apps.notifications",
    "apps.incidents",
    "apps.workorders",
    "apps.maintenance",
    "apps.lifecycle",
    "apps.privacy",
    "apps.organization",
    "apps.catalogo",
    "apps.inspeccion",
    "apps.inventario",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "config.security.ContentSecurityPolicyMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = build_database_config(BASE_DIR)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "es-pe"

TIME_ZONE = "America/Lima"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
PRIVATE_MEDIA_ROOT = BASE_DIR / "private_media"

NOTIFICATION_MESSAGE_ID_DOMAIN = os.environ.get('NOTIFICATION_MESSAGE_ID_DOMAIN', 'incalpaca.local')
NOTIFICATION_DISPATCH_ENABLED = os.environ.get(
    'NOTIFICATION_DISPATCH_ENABLED', '0' if DEBUG else '1'
) == '1'
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)
CELERY_TASK_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TIMEZONE = TIME_ZONE
HEALTH_CHECK_TOKEN = os.environ.get("HEALTH_CHECK_TOKEN", "")
HEALTH_DISK_WARNING_PERCENT = int(os.environ.get("HEALTH_DISK_WARNING_PERCENT", "80"))
HEALTH_DISK_CRITICAL_PERCENT = int(os.environ.get("HEALTH_DISK_CRITICAL_PERCENT", "90"))
MONITORING_TLS_HOST = os.environ.get("MONITORING_TLS_HOST", "").strip()
MONITORING_TLS_PORT = int(os.environ.get("MONITORING_TLS_PORT", "443"))

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOWED_ORIGINS = env_list(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:5173,http://127.0.0.1:5173,http://localhost:8008,http://127.0.0.1:8008" if DEBUG else "",
)
CORS_ALLOW_HEADERS = (*default_headers, "x-frontend-origin", "idempotency-key")

# HTTPS y cookies: en desarrollo se mantienen desactivadas para 127.0.0.1.
SECURE_SSL_REDIRECT = os.environ.get("SECURE_SSL_REDIRECT", "1" if IS_PRODUCTION else "0") == "1"
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https") if IS_PRODUCTION else None
SESSION_COOKIE_SECURE = IS_PRODUCTION
CSRF_COOKIE_SECURE = IS_PRODUCTION
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "31536000" if IS_PRODUCTION else "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = IS_PRODUCTION
SECURE_HSTS_PRELOAD = IS_PRODUCTION
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
X_FRAME_OPTIONS = "DENY"
CONTENT_SECURITY_POLICY = os.environ.get(
    "CONTENT_SECURITY_POLICY",
    "default-src 'self'; base-uri 'self'; frame-ancestors 'none'; form-action 'self'; "
    "img-src 'self' data: blob:; font-src 'self' data:; style-src 'self' 'unsafe-inline'; "
    "script-src 'self' 'unsafe-inline'; connect-src 'self' http://localhost:* http://127.0.0.1:*; "
    "worker-src 'self' blob:" if DEBUG else
    "default-src 'self'; base-uri 'self'; frame-ancestors 'none'; form-action 'self'; "
    "img-src 'self' data: blob:; font-src 'self' data:; style-src 'self' 'unsafe-inline'; "
    "script-src 'self' 'unsafe-inline'; connect-src 'self'; worker-src 'self' blob:",
)

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_THROTTLE_CLASSES": (
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.ScopedRateThrottle",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "anon": "120/hour",
        "login": "10/minute",
        "public_report": "20/hour",
        "public_privacy": "10/hour",
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(hours=8),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
}

SPECTACULAR_SETTINGS = {
    "TITLE": "SGTB Incalpaca API",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "ENUM_NAME_OVERRIDES": {
        "RetirementMethodEnum": (
            ("VENTA", "Venta"),
            ("RECICLAJE", "Reciclaje"),
            ("DESECHO", "Desecho"),
            ("DONACION", "Donación"),
        ),
        "StatusFc6Enum": (
            ("RECIBIDA", "Recibida"),
            ("EN_REVISION", "En revisión"),
            ("RESUELTA", "Resuelta"),
            ("RECHAZADA", "Rechazada"),
        ),
        "Tipo766Enum": (
            ("individual", "Individual"),
            ("grupal", "Grupal"),
        ),
        "ApprovedMethodEnum": (
            ("POR_DEFINIR", "Por definir"),
            ("VENTA", "Venta"),
            ("RECICLAJE", "Reciclaje"),
            ("DESECHO", "Desecho"),
            ("DONACION", "Donación"),
        ),
    },
}

PUBLIC_FRONTEND_URL = os.environ.get("PUBLIC_FRONTEND_URL", "http://localhost:5173")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "SGTB Incalpaca <no-reply@incalpaca.test>")
# The generic variables take precedence in production, while the Brevo names
# keep existing deployments working without duplicating credentials.
EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.environ.get("EMAIL_HOST", os.environ.get("BREVO_SMTP_HOST", "smtp-relay.brevo.com"))
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", os.environ.get("BREVO_SMTP_PORT", "587")))
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", os.environ.get("BREVO_SMTP_USE_TLS", "1")) == "1"
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", os.environ.get("BREVO_SMTP_USERNAME", ""))
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", os.environ.get("BREVO_SMTP_PASSWORD", ""))
EMAIL_TIMEOUT = int(os.environ.get("EMAIL_TIMEOUT", "15"))
