# Generated by Django 5.2.16 on 2026-07-24 19:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=36, unique=True)),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EMITIDA', 'Emitida'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=12)),
                ('condition', models.CharField(max_length=40)),
                ('accessories', models.TextField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('checklist', models.JSONField(default=dict)),
                ('privacy_accepted', models.BooleanField(default=False)),
                ('template_version', models.CharField(default='1.1', max_length=20)),
                ('hash_sha256', models.CharField(blank=True, max_length=64)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_act', to='assets.assetassignment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=180)),
                ('mime_type', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('content_data_url', models.TextField(blank=True)),
                ('hash_sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='assignments.deliveryact')),
            ],
        ),
        migrations.CreateModel(
            name='DeliverySignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ENTREGA', 'Facility Management'), ('RECIBE', 'Receptor')], max_length=10)),
                ('method', models.CharField(choices=[('DIBUJADA', 'Firma dibujada'), ('CONFIRMACION', 'Confirmación digital'), ('ACTA_ESCANEADA', 'Acta escaneada')], max_length=16)),
                ('signer_name', models.CharField(max_length=160)),
                ('signer_role', models.CharField(max_length=120)),
                ('consent', models.BooleanField(default=False)),
                ('signature_data_url', models.TextField(blank=True)),
                ('session_reference', models.CharField(blank=True, max_length=64)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='assignments.deliveryact')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('act', 'role'), name='uq_delivery_signature_role')],
            },
        ),
    ]
