# Generated by Django 5.2.16 on 2026-07-27 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_material_modelo'),
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('individual', 'Individual'), ('grupal', 'Grupal')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('resultado_general', models.CharField(choices=[('apta', 'Apta'), ('requiere_reparacion', 'Requiere reparación'), ('dada_de_baja', 'Dada de baja')], max_length=25)),
                ('accion_tomada', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True, help_text='Para lotes, mencionar aquí código de pieza afectada si aplica.')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspecciones_realizadas', to='cuentas.usuario')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspecciones', to='catalogo.material')),
                ('pieza', models.ForeignKey(blank=True, help_text='Solo para inspección individual.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspecciones', to='catalogo.pieza')),
                ('piezas_lote', models.ManyToManyField(blank=True, help_text='Para inspección grupal, piezas incluidas en el lote (opcional, vacío si el material no tiene control individual, ej. brocas).', related_name='inspecciones_grupales', to='catalogo.pieza')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspeccion.plantillacriterio')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='inspeccion.plantillacriterio')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(choices=[('cumple', 'Cumple'), ('no_cumple', 'No cumple'), ('no_aplica', 'No aplica')], max_length=10)),
                ('observacion', models.CharField(blank=True, max_length=255)),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspeccion.criterio')),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='inspeccion.inspeccion')),
            ],
            options={
                'unique_together': {('inspeccion', 'criterio')},
            },
        ),
    ]
