# Generated by Django 5.2.16 on 2026-07-28 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_material_modelo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('individual', 'Individual'), ('grupal', 'Grupal')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('proxima_inspeccion', models.DateField(blank=True, null=True)),
                ('cantidad_inspeccionada', models.PositiveIntegerField(blank=True, null=True)),
                ('cantidad_apta', models.PositiveIntegerField(blank=True, null=True)),
                ('cantidad_no_apta', models.PositiveIntegerField(blank=True, null=True)),
                ('resultado_general', models.CharField(blank=True, choices=[('apta', 'Apta'), ('requiere_reparacion', 'Requiere reparación'), ('fuera_servicio', 'Fuera de servicio')], max_length=25)),
                ('accion_tomada', models.CharField(blank=True, choices=[('continua_servicio', 'Continúa en servicio'), ('enviar_reparacion', 'Enviar a reparación'), ('retirar_servicio', 'Retirar del servicio'), ('dar_baja', 'Dar de baja'), ('reemplazar', 'Reemplazar')], max_length=25)),
                ('observaciones', models.TextField(blank=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspecciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspecciones', to='catalogo.material')),
                ('pieza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspecciones', to='catalogo.pieza')),
                ('piezas_lote', models.ManyToManyField(blank=True, related_name='inspecciones_grupales', to='catalogo.pieza')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspeccion.plantillacriterio')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='inspeccion.plantillacriterio')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(choices=[('cumple', 'Cumple'), ('no_cumple', 'No cumple'), ('no_aplica', 'No aplica')], max_length=10)),
                ('observacion', models.CharField(blank=True, max_length=255)),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspeccion.criterio')),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='inspeccion.inspeccion')),
            ],
            options={
                'unique_together': {('inspeccion', 'criterio')},
            },
        ),
    ]
