# Generated by Django 5.2.16 on 2026-07-27 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_material_modelo'),
        ('inspeccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccion',
            name='cantidad_apta',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='cantidad_inspeccionada',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='cantidad_no_apta',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='proxima_inspeccion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='accion_tomada',
            field=models.CharField(blank=True, choices=[('continua_servicio', 'Continúa en servicio'), ('enviar_reparacion', 'Enviar a reparación'), ('retirar_servicio', 'Retirar del servicio'), ('dar_baja', 'Dar de baja'), ('reemplazar', 'Reemplazar')], max_length=25),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='pieza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspecciones', to='catalogo.pieza'),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='piezas_lote',
            field=models.ManyToManyField(blank=True, related_name='inspecciones_grupales', to='catalogo.pieza'),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='resultado_general',
            field=models.CharField(blank=True, choices=[('apta', 'Apta'), ('requiere_reparacion', 'Requiere reparación'), ('fuera_servicio', 'Fuera de servicio')], max_length=25),
        ),
    ]
