# Generated by Django 5.2.16 on 2026-08-10 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_material_periodicidad_inspeccion_dias_pieza_detalle'),
        ('inspeccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanInspeccionAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('aprobado', 'Aprobado'), ('cerrado', 'Cerrado')], default='borrador', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-anio'],
            },
        ),
        migrations.CreateModel(
            name='ProgramacionInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodicidad_dias', models.PositiveIntegerField()),
                ('fecha_programada', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('realizada', 'Realizada')], default='pendiente', max_length=10)),
                ('inspeccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programacion', to='inspeccion.inspeccion')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programaciones_inspeccion', to='catalogo.material')),
                ('pieza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programaciones_inspeccion', to='catalogo.pieza')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones', to='inspeccion.planinspeccionanual')),
            ],
            options={
                'ordering': ['fecha_programada'],
            },
        ),
    ]
