# Generated by Django 5.2.16 on 2026-08-12 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_almacen_material_almacen'),
        ('inspeccion', '0002_planinspeccionanual_programacioninspeccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccion',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspecciones', to='catalogo.almacen'),
        ),
    ]
