# Generated by Django 5.2.16 on 2026-08-12 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0015_alter_material_almacen'),
        ('inspeccion', '0003_inspeccion_almacen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspeccion',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspecciones', to='catalogo.almacen'),
        ),
    ]
