# Generated by Django 5.2.16 on 2026-08-13 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0018_alter_categoria_almacen'),
        ('inspeccion', '0004_alter_inspeccion_almacen'),
    ]

    operations = [
        migrations.AddField(
            model_name='planinspeccionanual',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planes_inspeccion_anual', to='catalogo.almacen'),
        ),
        migrations.AddField(
            model_name='programacioninspeccion',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programaciones_por_almacen', to='catalogo.almacen'),
        ),
        migrations.AlterField(
            model_name='planinspeccionanual',
            name='anio',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='planinspeccionanual',
            unique_together={('anio', 'almacen')},
        ),
    ]
