# Generated by Django 5.2.16 on 2026-08-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspeccion', '0007_documentoinspeccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccion',
            name='referencia_orden',
            field=models.CharField(blank=True, help_text="Código de la orden asociada a esta inspección, ej. 'OT-2026-045', 'OL-2026-012', 'OP-2026-003'. Campo opcional, para trazabilidad con el sistema de órdenes.", max_length=50, verbose_name='Referencia OT/OL/OP'),
        ),
    ]
