# Generated by Django 5.2.16 on 2026-08-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspeccion', '0008_inspeccion_referencia_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccion',
            name='area_trabajo',
            field=models.CharField(blank=True, default='Facility Management', help_text='Lugar o área donde se realizó la inspección.', max_length=150, verbose_name='Área de trabajo / Lugar'),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='frecuencia',
            field=models.CharField(blank=True, choices=[('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('anual', 'Anual')], default='trimestral', max_length=20, verbose_name='Frecuencia planificada'),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='modalidad',
            field=models.CharField(choices=[('planificada', 'Planificada'), ('no_planificada', 'No planificada')], default='planificada', help_text='Planificada o No planificada', max_length=20, verbose_name='Tipo de inspección'),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='tipos_herramientas',
            field=models.JSONField(blank=True, default=list, help_text='Lista de tipos de herramientas manuales inspeccionadas (ej. Golpe, Corte, Cohesión, etc.).', verbose_name='Tipos de herramientas manuales'),
        ),
    ]
