# Generated by Django 5.2.16 on 2026-08-21 16:33

import django.utils.timezone
from django.db import migrations, models


def poblar_codigos_inspecciones_existentes(apps, schema_editor):
    Inspeccion = apps.get_model('inspeccion', 'Inspeccion')
    qs = Inspeccion.objects.filter(models.Q(codigo_inspeccion__isnull=True) | models.Q(codigo_inspeccion="")).order_by('id')
    for idx, insp in enumerate(qs, start=1):
        f = getattr(insp, 'fecha', None) or django.utils.timezone.now()
        yy = str(f.year)[-2:]
        mm = f"{f.month:02d}"
        insp.codigo_inspeccion = f"FOR-SST-{yy}{mm}-{idx:05d}"
        insp.save(update_fields=['codigo_inspeccion'])


class Migration(migrations.Migration):

    dependencies = [
        ('inspeccion', '0009_inspeccion_tipos_herramientas_y_modalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccion',
            name='area',
            field=models.CharField(blank=True, help_text="Área o sección de planta donde se realizó la inspección (ej. 'Hilandería').", max_length=150),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='codigo_inspeccion',
            field=models.CharField(blank=True, help_text='Código correlativo mensual (ej. FOR-SST-2608-00001). Se genera automáticamente.', max_length=30, null=True, unique=True),
        ),
        migrations.RunPython(poblar_codigos_inspecciones_existentes, migrations.RunPython.noop),
        migrations.AddField(
            model_name='inspeccion',
            name='tipo_inspeccion',
            field=models.CharField(choices=[('planificada', 'Planificada'), ('no_planificada', 'No planificada')], default='planificada', help_text='Naturaleza de la inspección: planificada o no planificada.', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
