# Generated by Django 5.2.16 on 2026-08-21 16:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspeccion', '0009_inspeccion_tipos_herramientas_y_modalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccion',
            name='area',
            field=models.CharField(blank=True, help_text="Área o sección de planta donde se realizó la inspección (ej. 'Hilandería').", max_length=150),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='codigo_inspeccion',
            field=models.CharField(blank=True, help_text='Código correlativo mensual (ej. FOR-SST-2608-00001). Se genera automáticamente.', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='tipo_inspeccion',
            field=models.CharField(choices=[('planificada', 'Planificada'), ('no_planificada', 'No planificada')], default='planificada', help_text='Naturaleza de la inspección: planificada o no planificada.', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
