# Generated by Django 5.2.16 on 2026-08-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspeccion', '0010_inspeccion_area_codigo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspeccion',
            name='frecuencia',
            field=models.CharField(blank=True, default='Trimestral', max_length=50, verbose_name='Frecuencia planificada'),
        ),
    ]
