# Generated by Django 5.2.16 on 2026-08-27 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspeccion', '0011_alter_inspeccion_frecuencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacionInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100)),
                ('nombre', models.CharField(max_length=200)),
                ('observacion_encontrada', models.TextField()),
                ('accion_recomendada', models.CharField(blank=True, help_text='Solo aplica a plantilla Manual', max_length=255)),
                ('estado', models.CharField(blank=True, help_text='Solo aplica a plantilla Manual', max_length=100)),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_con_observacion', to='inspeccion.inspeccion')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
