import { CalendarBlank, CheckCircle, Clock, Lightning, UsersThree } from "@phosphor-icons/react";
import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { listTechnicians, type Technician } from "@/modules/accounts/technicianRepository";
import { listWorkRequests } from "@/modules/incidents/incidentRepository";
import { listWorkOrders } from "@/modules/workorders/workOrderRepository";

function specialtyMatch(specialty: string, type: string) { const value = `${specialty} ${type}`.toLowerCase(); return ["electric", "gasfit", "carpint", "sold", "pint", "clima"].some((word) => value.includes(word)); }
function hours(value: number) { return `${Math.round(value * 10) / 10} h`; }

export function AssignmentRecommendationsPage() {
  const [technicians, setTechnicians] = useState<Technician[]>([]); const [orders, setOrders] = useState<Awaited<ReturnType<typeof listWorkOrders>>>([]); const [requests, setRequests] = useState<Awaited<ReturnType<typeof listWorkRequests>>>([]);
  useEffect(() => { void Promise.all([listTechnicians(), listWorkOrders(), listWorkRequests()]).then(([people, workOrders, workRequests]) => { setTechnicians(people.filter((person) => person.active)); setOrders(workOrders); setRequests(workRequests); }); }, []);
  const ready = requests.filter((request) => request.status === "APROBADA");
  const results = useMemo(() => ready.map((request) => ({ request, candidates: technicians.map((person) => { const assigned = orders.filter((order) => order.operatorId === person.id && order.scheduledDate >= new Date().toISOString().slice(0, 10) && !["CERRADA", "CANCELADA"].includes(order.status)); const scheduledHours = assigned.reduce((sum, order) => sum + order.plannedHours, 0); const matching = specialtyMatch(person.specialty, request.requestType); const urgency = request.requesterPriority === "EMERGENCIA" ? 14 : request.requesterPriority === "URGENTE" ? 9 : 4; const score = Math.max(0, 100 - scheduledHours * 9 + (matching ? 22 : 0) + urgency); return { person, scheduledHours, matching, score, reason: `${matching ? "Especialidad compatible" : "Especialidad general"} · ${hours(scheduledHours)} ya programadas` }; }).sort((a, b) => b.score - a.score).slice(0, 3) })), [ready, technicians, orders]);
  return <section className="recommendations-page"><header className="page-heading"><div><p className="breadcrumb">Administración / Planificación</p><h1>Asignaciones recomendadas</h1><p>Propuesta informada por especialidad, carga programada y prioridad. No realiza asignaciones automáticamente.</p></div></header><article className="recommendation-explainer"><CheckCircle size={22} /><span><strong>Control del planner:</strong> la recomendación solo orienta. La OT se crea y confirma manualmente.</span></article>{results.length ? <div className="recommendation-list">{results.map(({ request, candidates }) => <article key={request.id} className="recommendation-case"><header><div><span>{request.code}</span><h2>{request.assetDisplayCode || request.assetCode || "Reporte sin bien asociado"}</h2><p>{request.description}</p></div><b className={`priority-${request.requesterPriority.toLowerCase()}`}><Lightning size={15} />Prioridad {request.requesterPriority.toLowerCase()}</b></header><div className="recommendation-candidates">{candidates.map((candidate, index) => <div key={candidate.person.id}><span className="recommendation-rank">{index + 1}</span><div><strong>{candidate.person.full_name}</strong><small>{candidate.person.specialty || "Sin especialidad"}</small><p>{candidate.reason}</p></div><div className="recommendation-score"><b>{candidate.score}</b><small>afinidad</small></div><span className={`status ${candidate.scheduledHours >= 8 ? "status-warning" : "status-success"}`}><Clock size={14} />{hours(candidate.scheduledHours)}</span></div>)}</div><footer><span><CalendarBlank size={16} />Revisa la hora disponible antes de confirmar.</span><Link className="button button-primary" to={`/ordenes-trabajo/nueva/${request.id}`}><UsersThree size={17} />Preparar asignación</Link></footer></article>)}</div> : <article className="data-panel recommendation-empty"><CheckCircle size={28} /><h2>No hay reportes listos para asignar</h2><p>Las recomendaciones aparecerán después de que el planner apruebe un reporte.</p></article>}</section>;
}
