# Generated by Django 5.2.16 on 2026-08-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacenode',
            name='node_type',
            field=models.CharField(choices=[('MACRO_AREA', 'Macroárea'), ('SECTOR', 'Sector'), ('BUILDING', 'Edificio'), ('LEVEL', 'Nivel'), ('AREA', 'Área'), ('MODULE', 'Módulo'), ('ENVIRONMENT', 'Ambiente'), ('SUB_ENVIRONMENT', 'Sub-ambiente o Zona'), ('POINT', 'Punto o ubicación específica')], max_length=20),
        ),
    ]
