# Generated by Django 5.2.16 on 2026-08-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_alter_spacenode_node_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacenode',
            name='node_type',
            field=models.CharField(choices=[('MACRO_AREA', 'Área Macro'), ('AREA', 'Área'), ('MODULE', 'Módulo de trabajo')], max_length=20),
        ),
    ]
