# Generated by Django 5.2.16 on 2026-08-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0003_alter_spacenode_node_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacenode',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='space_photos/'),
        ),
    ]
