# Generated by Django 6.0.4 on 2026-07-27 19:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_alter_asset_assignment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=24, unique=True)),
                ('request_type', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('requester_priority', models.CharField(default='MEDIA', max_length=20)),
                ('project', models.BooleanField(default=False)),
                ('location_snapshot', models.JSONField(default=dict)),
                ('evidence', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('RECIBIDA', 'Recibida'), ('EN_REVISION', 'En revisión'), ('APROBADA', 'Aprobada para atención'), ('RECHAZADA', 'Atención no aprobada'), ('EN_ATENCION', 'En atención'), ('CERRADA', 'Cerrada')], default='RECIBIDA', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='assets.asset')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
