# Generated by Django 5.2.16 on 2026-08-03 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_incident_public_request_fields'),
        ('incidents', '0002_normalize_location_markers'),
    ]

    operations = [
    ]
