# Generated by Django 5.2.16 on 2026-08-03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0003_merge_20260803_0853"),
        ("incidents", "0003_public_reporter_fields"),
    ]

    operations = []