# Generated by Django 5.2.16 on 2026-07-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('rol', models.CharField(choices=[('trabajador', 'Trabajador/Operario'), ('encargado', 'Encargado de Almacén'), ('admin', 'Administrador')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
