# Generated by Django 6.0.4 on 2026-07-27 19:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('worker_code', models.CharField(max_length=40, unique=True)),
                ('role', models.CharField(choices=[('ADMINISTRADOR', 'Administrador / FM'), ('TECNICO', 'Técnico'), ('SUPERVISOR', 'Supervisor'), ('SOLICITANTE', 'Solicitante')], max_length=20)),
                ('specialty', models.CharField(blank=True, max_length=100)),
                ('must_change_password', models.BooleanField(default=True)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('last_access', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
