# Generated by Django 5.2.16 on 2026-08-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_almacenero_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountprofile',
            name='role',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador / FM'), ('TECNICO', 'Técnico'), ('SUPERVISOR', 'Supervisor'), ('SOLICITANTE', 'Solicitante'), ('ALMACENERO', 'Almacenero'), ('INSPECTOR', 'Inspector')], max_length=20),
        ),
    ]