# Generated by Django 5.2.16 on 2026-08-11 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_accountprofile_role'),
        ('accounts', '0003_technician_compensation'),
    ]

    operations = [
    ]
