# Generated by Django 5.2.16 on 2026-08-11 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20260810_2154'),
        ('accounts', '0004_merge_20260811_1051'),
    ]

    operations = [
    ]
