# Generated by Django 5.2.16 on 2026-08-12 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20260811_1436'),
        ('catalogo', '0018_alter_categoria_almacen'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='almacen',
            field=models.ForeignKey(blank=True, help_text='Almacén asignado. Requerido si el rol es Almacenero o Inspector.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles', to='catalogo.almacen'),
        ),
    ]
