# Generated by Django 5.2.16 on 2026-08-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_accountprofile_almacen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountprofile',
            name='role',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador / FM'), ('TECNICO', 'Técnico'), ('SUPERVISOR', 'Supervisor'), ('USUARIO', 'Usuario'), ('ALMACENERO', 'Almacenero'), ('INSPECTOR', 'Inspector')], max_length=20),
        ),
    ]
