# Generated by Django 5.2.16 on 2026-08-13 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_accountprofile_almacen'),
        ('accounts', '0006_accountworkercode'),
    ]

    operations = [
    ]
