# Generated by Django 5.2.16 on 2026-08-21 15:30

from django.db import migrations

def update_solicitante_to_usuario(apps, schema_editor):
    AccountProfile = apps.get_model('accounts', 'AccountProfile')
    AccountProfile.objects.filter(role='SOLICITANTE').update(role='USUARIO')

def reverse_solicitante_to_usuario(apps, schema_editor):
    AccountProfile = apps.get_model('accounts', 'AccountProfile')
    AccountProfile.objects.filter(role='USUARIO').update(role='SOLICITANTE')

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_accountprofile_role'),
    ]

    operations = [
        migrations.RunPython(update_solicitante_to_usuario, reverse_solicitante_to_usuario),
    ]
