# Generated by Django 5.2.16 on 2026-08-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20260821_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='initial_password',
            field=models.CharField(blank=True, default='', help_text='Última clave temporal asignada por el administrador', max_length=128),
        ),
    ]
