import { ArrowClockwise, Bell, CheckCircle, WarningCircle } from "@phosphor-icons/react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useAuth } from "@/modules/accounts/AuthContext";
import { type EmailNotification, listNotifications, markNotificationRead, retryNotification } from "@/modules/notifications/notificationRepository";

function dateTime(value: string | null) { return value ? new Intl.DateTimeFormat("es-PE", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—"; }
const statusLabel = { PENDIENTE: "En cola", ENVIADA: "Enviada", ERROR: "Error", CANCELADA: "Cancelada" } as const;

export function NotificationsPage() {
  const { user } = useAuth(); const isAdmin = user?.role === "ADMINISTRADOR";
  const [items, setItems] = useState<EmailNotification[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [showHistory, setShowHistory] = useState(false); const [retrying, setRetrying] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { setItems(await listNotifications({ includeAll: isAdmin && showHistory })); } catch { setError("No se pudo cargar tu bandeja de notificaciones."); } finally { setLoading(false); } }, [isAdmin, showHistory]);
  useEffect(() => { void load(); }, [load]);
  const unread = useMemo(() => items.filter((item) => !item.readAt).length, [items]); const failures = items.filter((item) => item.status === "ERROR").length;
  async function read(item: EmailNotification) { if (item.readAt) return; try { const updated = await markNotificationRead(item.id); setItems((current) => current.map((entry) => entry.id === updated.id ? updated : entry)); } catch { setError("No se pudo actualizar la notificación."); } }
  async function retry(item: EmailNotification) { setRetrying(item.id); try { const updated = await retryNotification(item.id); setItems((current) => current.map((entry) => entry.id === updated.id ? updated : entry)); } catch { setError("No se pudo reprogramar el correo."); } finally { setRetrying(""); } }
  return <section className="notifications-page"><header className="page-heading"><div><p className="breadcrumb">Comunicaciones</p><h1>Notificaciones</h1><p>Alertas operativas y comunicaciones importantes dirigidas a tu usuario.</p></div></header>
    <div className="notification-summary" aria-label="Resumen de notificaciones"><article><span>Sin leer</span><strong>{unread}</strong><small>Requieren tu atención</small></article><article><span>Registradas</span><strong>{items.length}</strong><small>En esta bandeja</small></article><article className={failures ? "has-errors" : ""}><span>Con error de correo</span><strong>{failures}</strong><small>{isAdmin ? "Puedes reintentar el envío" : "En seguimiento por FM"}</small></article></div>
    <article className="data-panel notification-panel"><header><div><Bell size={22} /><div><h2>{showHistory ? "Historial general de correos" : "Tu bandeja"}</h2><p>{showHistory ? "Vista administrativa de todos los envíos del sistema." : "Al abrir un aviso se marca como leído. Los correos se reservan para hitos y alertas importantes."}</p></div></div><div className="notification-toolbar">{isAdmin && <label className="switch-row compact-switch"><input type="checkbox" checked={showHistory} onChange={(event) => setShowHistory(event.target.checked)} /><span>Ver todos</span></label>}<button className="button button-secondary" type="button" onClick={() => void load()} disabled={loading}><ArrowClockwise size={17} />Actualizar</button></div></header>
      {loading ? <div className="loading-panel">Cargando notificaciones…</div> : error ? <div className="form-error"><WarningCircle />{error}</div> : !items.length ? <div className="notification-empty"><CheckCircle size={30} /><strong>Todo está al día</strong><span>Las asignaciones, reportes, revisiones y alertas aparecerán aquí.</span></div> : <div className="notification-list">{items.map((item) => <article key={item.id} className={`notification-row ${!item.readAt ? "is-unread" : ""}`}><button type="button" className="notification-row-main" onClick={() => void read(item)}><div><strong>{item.subject}</strong><p>{item.body}</p></div><span className={`status status-${item.status === "ERROR" ? "error" : item.status === "PENDIENTE" ? "warning" : item.status === "ENVIADA" ? "success" : "neutral"}`}>{statusLabel[item.status]}</span></button><footer><span>{item.readAt ? `Leída ${dateTime(item.readAt)}` : `Nueva · ${dateTime(item.createdAt)}`}</span>{item.status === "ERROR" && isAdmin && <button className="button button-secondary" type="button" onClick={() => void retry(item)} disabled={retrying === item.id}><ArrowClockwise size={16} />{retrying === item.id ? "Reprogramando…" : "Reintentar correo"}</button>}</footer></article>)}</div>}
    </article></section>;
}
