# Generated by Django 6.0.4 on 2026-07-27 19:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=24, unique=True)),
                ('specialty', models.CharField(max_length=100)),
                ('admin_priority', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('EN_PROCESO', 'En proceso'), ('PENDIENTE_DE_SUPERVISION', 'Pendiente de supervisión'), ('PENDIENTE_DE_VALIDACION', 'Pendiente de validación'), ('PENDIENTE_DE_CONFORMIDAD', 'Pendiente de conformidad'), ('CERRADA', 'Cerrada'), ('DEVUELTA', 'Devuelta'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', max_length=32)),
                ('scheduled_date', models.DateField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('administrator_notes', models.TextField(blank=True)),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0)),
                ('advances', models.JSONField(default=list)),
                ('diagnosis', models.JSONField(default=dict)),
                ('supervisor_validation', models.JSONField(default=dict)),
                ('administrator_validation', models.JSONField(default=dict)),
                ('conformity', models.JSONField(default=dict)),
                ('recommendation_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='work_order', to='incidents.incident')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervised_orders', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technical_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
