# Generated by Django 5.2.16 on 2026-08-09 01:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_merge_20260807_2014'),
        ('workorders', '0014_workorder_order_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workordercost',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='WorkOrderMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('USADO', 'Usado'), ('NECESARIO_NO_BLOQUEANTE', 'Necesario (no bloqueante)')], default='USADO', max_length=24)),
                ('es_bloqueante', models.BooleanField(default=False, help_text='True cuando el técnico llega al punto en que ya no puede continuar sin este material (solo aplica cuando tipo=NECESARIO_NO_BLOQUEANTE).')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos_en_ot', to='catalogo.material')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiales_registrados_en_ot', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiales_usados', to='workorders.workorder')),
            ],
            options={
                'verbose_name': 'Material en OT',
                'verbose_name_plural': 'Materiales en OT',
                'ordering': ('creado_en',),
            },
        ),
    ]
