# Generated by Django 5.2.16 on 2026-08-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0015_work_order_material_and_cost_amount_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordermaterial',
            name='porcentaje_requerido',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Porcentaje de avance de la OT en que el material es requerido (0-100).', null=True),
        ),
    ]
