# Generated by Django 5.2.16 on 2026-08-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0016_work_order_material_porcentaje_requerido'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordermaterial',
            name='adquirido',
            field=models.BooleanField(default=False, help_text='True cuando el administrador confirma que el material bloqueante ya fue comprado/conseguido.'),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='adquirido_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]