# Generated by Django 5.2.16 on 2026-08-11 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0017_workorder_pending_reschedule'),
        ('workorders', '0017_workordermaterial_adquirido_and_more'),
    ]

    operations = [
    ]
