# Generated by Django 5.2.16 on 2026-08-11 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0018_merge_20260810_2154'),
        ('workorders', '0018_merge_20260810_2314'),
    ]

    operations = [
    ]
