# Generated by Django 5.2.16 on 2026-08-13 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0018_merge_20260811_1051'),
        ('workorders', '0019_merge_20260811_0908'),
    ]

    operations = [
    ]
