# Generated by Django 5.2.16 on 2026-08-13 02:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0019_merge_20260811_0908'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='almaceneros_autorizados',
            field=models.ManyToManyField(blank=True, help_text='Almaceneros que pueden ver y usar esta OT en el módulo de movimientos de inventario. Gestionado por el ADMINISTRADOR, ya que una OT solo debe ser visible para el/los almacenero(s) del almacén al que corresponde.', related_name='ordenes_almacen_autorizadas', to=settings.AUTH_USER_MODEL),
        ),
    ]