# Generated by Django 5.2.16 on 2026-08-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0020_almaceneros_autorizados'),
        ('workorders', '0020_merge_20260813_1359'),
    ]

    operations = [
    ]
