# Generated by Django 5.2.16 on 2026-08-13 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0020_merge_20260813_1359'),
        ('workorders', '0021_material_cost_sync_and_unit_price'),
    ]

    operations = [
    ]
