# Generated by Django 5.2.16 on 2026-08-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0022_reporttemplate_is_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordermaterial',
            name='cantidad_comprometida',
            field=models.PositiveIntegerField(default=0, help_text='Suma de lo ya solicitado (pendiente o aprobado) o despachado directamente contra este renglón. cantidad - cantidad_comprometida = lo que aún falta por despachar.'),
        ),
    ]
