# Generated by Django 5.2.16 on 2026-07-29 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0003_subcategoria_plantilla_inspeccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('salida', 'Salida'), ('entrada', 'Entrada'), ('baja', 'Baja')], max_length=10)),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Para materiales sin control individual, cantidad que sale/entra/se da de baja. Para piezas individuales, siempre 1.')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('referencia_externa', models.CharField(blank=True, help_text="Código de Orden de Trabajo/Solicitud de otro módulo, ej. 'OT-2026-045'.", max_length=50)),
                ('lote_id', models.CharField(blank=True, help_text='Identificador compartido cuando varios movimientos pertenecen a la misma salida de un estuche completo (contenedor + hijas).', max_length=40)),
                ('observaciones', models.TextField(blank=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='catalogo.material')),
                ('pieza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='catalogo.pieza')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
