# Generated by Django 5.2.16 on 2026-08-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='cantidad_cajas',
            field=models.PositiveIntegerField(blank=True, help_text="Si el material se maneja por caja, número de cajas que originaron este movimiento. 'cantidad' sigue siendo el total en unidades (cajas × unidades/caja).", null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, help_text='Para materiales sin control individual, cantidad que sale/entra/se da de baja SIEMPRE expresada en unidades. Para piezas individuales, siempre 1.'),
        ),
    ]
