# Generated by Django 5.2.16 on 2026-08-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_solicitudmovimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='cantidad_cajas',
            field=models.PositiveIntegerField(blank=True, help_text="Si el material se maneja por empaque, número de empaques que originaron este movimiento. 'cantidad' sigue siendo el total en unidades (empaques × unidades/empaque).", null=True),
        ),
    ]
