# Generated by Django 5.2.16 on 2026-08-12 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_movimiento_cantidad_cajas'),
        ('workorders', '0019_merge_20260811_0908'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudmovimiento',
            name='motivo_no_entrega',
            field=models.TextField(blank=True, help_text='Razón por la que este item específico no fue entregado en una aprobación parcial.'),
        ),
        migrations.AddField(
            model_name='solicitudmovimiento',
            name='work_order',
            field=models.ForeignKey(blank=True, help_text='Orden de Trabajo que originó esta solicitud (solo en flujo de aprobación).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_movimiento', to='workorders.workorder'),
        ),
        migrations.CreateModel(
            name='GrupoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_solicitud_creados', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(blank=True, help_text='Orden de Trabajo que origina este pedido de materiales (opcional).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grupos_solicitud', to='workorders.workorder')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='solicitudmovimiento',
            name='grupo',
            field=models.ForeignKey(blank=True, help_text='Grupo de solicitudes al que pertenece este item (None = solicitud unitaria suelta).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventario.gruposolicitud'),
        ),
    ]
