# Generated by Django 5.2.16 on 2026-08-13 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_movimiento_almacen'),
        ('inventario', '0005_gruposolicitud_and_solicitudmovimiento_v2'),
    ]

    operations = [
    ]
