# Generated by Django 5.2.16 on 2026-08-14 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_merge_20260813_1359'),
        ('inventario', '0006_movimiento_unidad_conversion'),
    ]

    operations = [
    ]
